from .enum import Enum


class ErrorCodes(Enum):
    UNKNOWN = 'Unknown'
    BAD_CERTIFICATE = 'BadCertificate'
    SUBSCRIPTION_NOT_FOUND = 'SubscriptionNotFound'
    SUBSCRIPTION_REQUIRED = 'SubscriptionRequired'
    APPLICATION_NOT_FOUND = 'ApplicationNotFound'
    BAD_SUBSCRIPTION = 'BadSubscription'
    NORMAL_SUBSCRIPTION_REQUIRED = 'NormalSubscriptionRequired'
    NOT_REGISTERED = 'NotRegistered'
    AGENT_NOT_FOUND = 'AgentNotFound'
    AGENT_IS_NOT_USER = 'AgentIsNotUser'
    INVITE_NOT_FOUND = 'InviteNotFound'
    APPLICATION_KEY_NOT_FOUND = 'ApplicationKeyNotFound'
    APPLICATION_DELETED = 'ApplicationDeleted'
    APPLICATION_NAME_EXISTS = 'ApplicationNameExists'
    USER_NOT_FOUND = 'UserNotFound'
    INVALID_CLAIM_CODE = 'InvalidClaimCode'
    SEARCH_NOT_SUPPORTED = 'SearchNotSupported'
    EMAIL_DISABLED = 'EmailDisabled'
    HTTPS_REQUIRED = 'HttpsRequired'
    ROLE_MISSING = 'RoleMissing'
    UPLOAD_NOT_FOUND = 'UploadNotFound'
    PUBLIC_KEY_AUTHENTICATION_EXPIRED = 'PublicKeyAuthenticationExpired'
    NONCE_REUSED = 'NonceReused'
    INVALID_NONCE_SIGNATURE = 'InvalidNonceSignature'
    PUBLIC_KEY_AUTHENTICATION_SESSION_MISSING = 'PublicKeyAuthenticationSessionMissing'
    INVALID_PUBLIC_KEY_AUTHENTICATION_SESSION = 'InvalidPublicKeyAuthenticationSession'
    CHILD_NAMESPACE_NOT_FOUND = 'ChildNamespaceNotFound'
    OIDC_DISABLED = 'OidcDisabled'
    ROOT_PASSWORD_HASH_NOT_FOUND = 'RootPasswordHashNotFound'
    GRANT_ID_ERROR = 'GrantIdError'
    INVALID_SCAN_SESSION_TICKET = 'InvalidScanSessionTicket'
    SCAN_SESSION_NOT_FOUND = 'ScanSessionNotFound'
    DOCUMENT_NOT_FOUND = 'DocumentNotFound'
    SCAN_SESSION_STATE_MISSING = 'ScanSessionStateMissing'
    SCAN_SESSION_STATE_EXPIRED = 'ScanSessionStateExpired'
    SCAN_SESSION_COMPLETED = 'ScanSessionCompleted'
    SCAN_SESSION_EXPIRED = 'ScanSessionExpired'
    INVALID_SCAN_SESSION_STATE = 'InvalidScanSessionState'
    INVALID_ISO_8601_DATE = 'InvalidIso8601Date'
    SCANNED_DOCUMENT_NOT_UPLOADED = 'ScannedDocumentNotUploaded'
    METADATA_NOT_SUBMITTED = 'MetadataNotSubmitted'
    DOCUMENT_SIGNATURE_NOT_STARTED = 'DocumentSignatureNotStarted'
    DOCUMENT_SIGNATURE_NOT_SUBMITTED = 'DocumentSignatureNotSubmitted'
    KEYWORDS_REQUIRED = 'KeywordsRequired'
    KEYWORD_TOO_lONG = 'KeywordTooLong'
    INVALID_METADATA_PRESETS = 'InvalidMetadataPresets'
    INVALID_CAPTCHA = 'InvalidCaptcha'

__all__ = ['ErrorCodes']